### PR TITLE
M13T015 - Force Combination Test

### PR DESCRIPTION
**Pull request by pkubanek**
- M13T015, MTM1Movements.applyOffsetForces
- Added active forces and offsets

### CODE REVIEW

**Review by hdrass — CHANGES_REQUESTED** [review]
All good, except for:
```
python3.10 M13T015.py 
M13T-015: Active Optic Bending Mode Offsets
Starting up..  [#########################------------------------------------------------------------------------------]   25%  00:00:03
Bending Mode [5.0, 3.0, 1.5, 0.5, 0.1, 0.2, 0.05, 0.6, 0.1, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
E
======================================================================
ERROR: test_active_optic_bending_mode_offsets (__main__.M13T015)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/usr/local/lib/python3.10/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "/usr/local/lib/python3.10/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/hdrass/code-testing/ts_m1m3supporttesting/M13T015.py", line 143, in test_active_optic_bending_mode_offsets
    await self.m1m3.cmd_applyActiveOpticForcesByBendingModes.set_start(coefficients=bm)
AttributeError: 'Remote' object has no attribute 'cmd_applyActiveOpticForcesByBendingModes'

----------------------------------------------------------------------
Ran 1 test in 5.765s

FAILED (errors=1)

```

**Comment by pkubanek** [comment]
You need to checkout correct branch. I can do it for you if you are running it from pkubanek

Dne 10. 3. 2023 11:32 napsal uživatel Holger Drass ***@***.***>:

@hdrass requested changes on this pull request.

All good, except for:

python3.10 M13T015.py
M13T-015: Active Optic Bending Mode Offsets
Starting up..  [#########################------------------------------------------------------------------------------]   25%  00:00:03
Bending Mode [5.0, 3.0, 1.5, 0.5, 0.1, 0.2, 0.05, 0.6, 0.1, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
E
======================================================================
ERROR: test_active_optic_bending_mode_offsets (__main__.M13T015)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/usr/local/lib/python3.10/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "/usr/local/lib/python3.10/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/hdrass/code-testing/ts_m1m3supporttesting/M13T015.py", line 143, in test_active_optic_bending_mode_offsets
    await self.m1m3.cmd_applyActiveOpticForcesByBendingModes.set_start(coefficients=bm)
AttributeError: 'Remote' object has no attribute 'cmd_applyActiveOpticForcesByBendingModes'

----------------------------------------------------------------------
Ran 1 test in 5.765s

FAILED (errors=1)

**Comment by hdrass** [comment]
Oki, I see my  problem.


[hdrass@m1m3-dev ts_m1m3supporttesting]$

**Comment by hdrass** [comment]
Issues with M1M3 -TMA interlock keep me from testing right now. Code looks good. I approve here.

**Review by hdrass — APPROVED** [review]
Code looks good. More testing when TMA is ready.

**Pull request merged**
